COMMANDS = {
    "AB": {"mnemonic": "AB", "param_count": 0, "desc": "Main band to sub band"},
    "AC": {"mnemonic": "AC", "param_count": 0, "desc": "Antenna tuner control"},
    "AG": {"mnemonic": "AG", "param_count": 0, "desc": "AF gain"},
    "AI": {"mnemonic": "AI", "param_count": 0, "desc": "Auto information"},
    "AM": {"mnemonic": "AM", "param_count": 0, "desc": "Main band to memory channel"},
    "AN": {"mnemonic": "AN", "param_count": 0, "desc": "Antenna number"},
    "AO": {"mnemonic": "AO", "param_count": 0, "desc": "AMC output level"},
    "AV": {"mnemonic": "AV", "param_count": 0, "desc": "Anti VOX level"},
    "BA": {"mnemonic": "BA", "param_count": 0, "desc": "Sub band to main band"},
    "BC": {"mnemonic": "BC", "param_count": 0, "desc": "Auto notch"},
    "BD": {"mnemonic": "BD", "param_count": 0, "desc": "Band down"},
    "BI": {"mnemonic": "BI", "param_count": 0, "desc": "Break-in"},
    "BM": {"mnemonic": "BM", "param_count": 0, "desc": "Sub band to memory channel"},
    "BP": {"mnemonic": "BP", "param_count": 0, "desc": "Manual notch"},
    "BS": {"mnemonic": "BS", "param_count": 0, "desc": "Band select"},
    "BU": {"mnemonic": "BU", "param_count": 0, "desc": "Band up"},
    "BY": {"mnemonic": "BY", "param_count": 0, "desc": "Busy"},
    "CH": {"mnemonic": "CH", "param_count": 0, "desc": "Channel up/down"},
    "CN": {"mnemonic": "CN", "param_count": 0, "desc": "CTCSS/DCS number"},
    "CO": {"mnemonic": "CO", "param_count": 0, "desc": "Contour"},
    "CS": {"mnemonic": "CS", "param_count": 0, "desc": "CW spot"},
    "CT": {"mnemonic": "CT", "param_count": 0, "desc": "CTCSS"},
    "DA": {"mnemonic": "DA", "param_count": 0, "desc": "Dimmer"},
    "DN": {"mnemonic": "DN", "param_count": 0, "desc": "Down"},
    "DT": {"mnemonic": "DT", "param_count": 0, "desc": "Date and time"},
    "ED": {"mnemonic": "ED", "param_count": 0, "desc": "Encoder down"},
    "EM": {"mnemonic": "EM", "param_count": 0, "desc": "Encode memory"},
    "EN": {"mnemonic": "EN", "param_count": 0, "desc": "Encode"},
    "EU": {"mnemonic": "EU", "param_count": 0, "desc": "Encoder up"},
    "EX": {"mnemonic": "EX", "param_count": 0, "desc": "Menu"},
    "FA": {"mnemonic": "FA", "param_count": 9, "desc": "Frequency main band"},
    "FB": {"mnemonic": "FB", "param_count": 9, "desc": "Frequency sub band"},
    "FN": {"mnemonic": "FN", "param_count": 0, "desc": "Fine tuning"},
    "FR": {"mnemonic": "FR", "param_count": 0, "desc": "Function RX"},
    "FS": {"mnemonic": "FS", "param_count": 0, "desc": "Fast step"},
    "FT": {"mnemonic": "FT", "param_count": 0, "desc": "Function TX"},
    "GT": {"mnemonic": "GT", "param_count": 0, "desc": "AGC function"},
    "ID": {"mnemonic": "ID", "param_count": 0, "desc": "Identification"},
    "IF": {"mnemonic": "IF", "param_count": 0, "desc": "Information"},
    "IS": {"mnemonic": "IS", "param_count": 0, "desc": "IF-shift"},
    "KM": {"mnemonic": "KM", "param_count": 0, "desc": "Keyer memory"},
    "KP": {"mnemonic": "KP", "param_count": 0, "desc": "Key pitch"},
    "KR": {"mnemonic": "KR", "param_count": 0, "desc": "Keyer"},
    "KS": {"mnemonic": "KS", "param_count": 0, "desc": "Key speed"},
    "KY": {"mnemonic": "KY", "param_count": 0, "desc": "CW keying"},
    "LK": {"mnemonic": "LK", "param_count": 0, "desc": "Lock"},
    "LM": {"mnemonic": "LM", "param_count": 0, "desc": "Load message"},
    "MA": {"mnemonic": "MA", "param_count": 0, "desc": "Memory channel to main band"},
    "MB": {"mnemonic": "MB", "param_count": 0, "desc": "Memory channel to sub band"},
    "MC": {"mnemonic": "MC", "param_count": 0, "desc": "Memory channel"},
    "MD": {"mnemonic": "MD", "param_count": 0, "desc": "Mode"},
    "MG": {"mnemonic": "MG", "param_count": 0, "desc": "Mic gain"},
    "ML": {"mnemonic": "ML", "param_count": 0, "desc": "Monitor level"},
    "MR": {"mnemonic": "MR", "param_count": 0, "desc": "Memory read"},
    "MS": {"mnemonic": "MS", "param_count": 0, "desc": "Meter switch"},
    "MT": {"mnemonic": "MT", "param_count": 0, "desc": "Memory channel write/tag"},
    "MW": {"mnemonic": "MW", "param_count": 0, "desc": "Memory write"},
    "MX": {"mnemonic": "MX", "param_count": 0, "desc": "MOX set"},
    "NA": {"mnemonic": "NA", "param_count": 0, "desc": "Narrow"},
    "NB": {"mnemonic": "NB", "param_count": 0, "desc": "Noise blanker"},
    "NL": {"mnemonic": "NL", "param_count": 0, "desc": "Noise blanker level"},
    "NR": {"mnemonic": "NR", "param_count": 0, "desc": "Noise reduction"},
    "OI": {"mnemonic": "OI", "param_count": 0, "desc": "Opposite band information"},
    "OS": {"mnemonic": "OS", "param_count": 0, "desc": "Offset (Repeater Shift)"},
    "PA": {"mnemonic": "PA", "param_count": 0, "desc": "Pre-amp (IPO)"},
    "PB": {"mnemonic": "PB", "param_count": 0, "desc": "Play back"},
    "PC": {"mnemonic": "PC", "param_count": 0, "desc": "Power control"},
    "PL": {"mnemonic": "PL", "param_count": 0, "desc": "Speech processor level"},
    "PR": {"mnemonic": "PR", "param_count": 0, "desc": "Speech processor"},
    "PS": {"mnemonic": "PS", "param_count": 0, "desc": "Power switch"},
    "QI": {"mnemonic": "QI", "param_count": 0, "desc": "QMB store"},
    "QR": {"mnemonic": "QR", "param_count": 0, "desc": "QMB recall"},
    "QS": {"mnemonic": "QS", "param_count": 0, "desc": "Quick split"},
    "RA": {"mnemonic": "RA", "param_count": 0, "desc": "RF attenuator"},
    "RC": {"mnemonic": "RC", "param_count": 0, "desc": "Clar clear"},
    "RD": {"mnemonic": "RD", "param_count": 0, "desc": "Clar down"},
    "RF": {"mnemonic": "RF", "param_count": 0, "desc": "Roofing filter"},
    "RG": {"mnemonic": "RG", "param_count": 0, "desc": "RF gain"},
    "RI": {"mnemonic": "RI", "param_count": 0, "desc": "Radio information"},
    "RL": {"mnemonic": "RL", "param_count": 0, "desc": "Noise reduction level"},
    "RM": {"mnemonic": "RM", "param_count": 0, "desc": "Read meter"},
    "RS": {"mnemonic": "RS", "param_count": 0, "desc": "Radio status"},
    "RT": {"mnemonic": "RT", "param_count": 0, "desc": "Clar"},
    "RU": {"mnemonic": "RU", "param_count": 0, "desc": "Clar up"},
    "SC": {"mnemonic": "SC", "param_count": 0, "desc": "Scan"},
    "SD": {"mnemonic": "SD", "param_count": 0, "desc": "Semi break-in delay time"},
    "SF": {"mnemonic": "SF", "param_count": 0, "desc": "Sub dial"},
    "SH": {"mnemonic": "SH", "param_count": 0, "desc": "Width"},
    "SM": {"mnemonic": "SM", "param_count": 0, "desc": "S meter"},
    "SQ": {"mnemonic": "SQ", "param_count": 0, "desc": "Squelch level"},
    "SS": {"mnemonic": "SS", "param_count": 0, "desc": "Spectrum scope"},
    "ST": {"mnemonic": "ST", "param_count": 0, "desc": "Split"},
    "SV": {"mnemonic": "SV", "param_count": 0, "desc": "Swap VFO"},
    "SY": {"mnemonic": "SY", "param_count": 0, "desc": "Sync"},
    "TX": {"mnemonic": "TX", "param_count": 0, "desc": "TX set"},
    "UL": {"mnemonic": "UL", "param_count": 0, "desc": "Unlock"},
    "UP": {"mnemonic": "UP", "param_count": 0, "desc": "Up"},
    "VD": {"mnemonic": "VD", "param_count": 0, "desc": "VOX delay time"},
    "VG": {"mnemonic": "VG", "param_count": 0, "desc": "VOX gain"},
    "VM": {"mnemonic": "VM", "param_count": 0, "desc": "[V/M] key function"},
    "VS": {"mnemonic": "VS", "param_count": 0, "desc": "VFO select"},
    "VT": {"mnemonic": "VT", "param_count": 0, "desc": "VCT(VC tune)"},
    "VX": {"mnemonic": "VX", "param_count": 0, "desc": "VOX"},
    "XT": {"mnemonic": "XT", "param_count": 0, "desc": "TX clar"},
    "ZI": {"mnemonic": "ZI", "param_count": 0, "desc": "Zero in"},
}
